--MEMBER_STATUS 회원 상태 테이블 코드

INSERT INTO MEMBER_STATUS VALUES (101,'정상 유저');
INSERT INTO MEMBER_STATUS VALUES (102,'탈퇴 유저');
COMMIT;

--MEMBER_GRADE 회원 등급 테이블 코드
INSERT INTO MEMBER_GRADE VALUES (206,'아이언',1,100000);
INSERT INTO MEMBER_GRADE VALUES (205,'브론즈',0.99,300000);
INSERT INTO MEMBER_GRADE VALUES (204,'실버',0.95,500000);
INSERT INTO MEMBER_GRADE VALUES (203,'골드',0.9,1000000);
INSERT INTO MEMBER_GRADE VALUES (202,'플래티넘',0.85,2000000);
INSERT INTO MEMBER_GRADE VALUES (201,'다이아',0.8,9999999999);

COMMIT;

--PRODUCT_CATEGORY 상품 카테고리 종류 코드
INSERT INTO PRODUCT_CATEGORY VALUES(300,'ALL');

INSERT INTO PRODUCT_CATEGORY VALUES(310,'스킨케어');
INSERT INTO PRODUCT_CATEGORY VALUES(311,'클렌저');
INSERT INTO PRODUCT_CATEGORY VALUES(312,'트리트먼트');
INSERT INTO PRODUCT_CATEGORY VALUES(313,'토너');

INSERT INTO PRODUCT_CATEGORY VALUES(320,'바디 '||'&'|| ' 핸드');
INSERT INTO PRODUCT_CATEGORY VALUES(321,'핸드');
INSERT INTO PRODUCT_CATEGORY VALUES(322,'바디');

INSERT INTO PRODUCT_CATEGORY VALUES(330,'헤어');
INSERT INTO PRODUCT_CATEGORY VALUES(331,'샴푸');
INSERT INTO PRODUCT_CATEGORY VALUES(332,'컨디셔너');
INSERT INTO PRODUCT_CATEGORY VALUES(333,'트리트먼트');

INSERT INTO PRODUCT_CATEGORY VALUES(340,'향수');
INSERT INTO PRODUCT_CATEGORY VALUES(341,'미라세티');
INSERT INTO PRODUCT_CATEGORY VALUES(342,'에레미아');
INSERT INTO PRODUCT_CATEGORY VALUES(343,'로즈');
commit;


--PRODUCT_STATUS 상품 카테고리 종류 코드

INSERT INTO PRODUCT_STATUS VALUES(1001,'판매중');
INSERT INTO PRODUCT_STATUS VALUES(1002,'품절');
commit;


--ORDER_STATUS 주문 상태코드

INSERT INTO ORDER_STATUS VALUES(401,'결제완료');
INSERT INTO ORDER_STATUS VALUES(402,'구매확정');
INSERT INTO ORDER_STATUS VALUES(403,'결제취소');
INSERT INTO ORDER_STATUS VALUES(404,'교환');
INSERT INTO ORDER_STATUS VALUES(405,'반품');
commit;

--DELIVERY_STATUS 배송 상태코드

INSERT INTO DELIVERY_STATUS VALUES(501,'상품준비중');
INSERT INTO DELIVERY_STATUS VALUES(502,'배송준비중');
INSERT INTO DELIVERY_STATUS VALUES(503,'배송중');
INSERT INTO DELIVERY_STATUS VALUES(504,'배송완료');
INSERT INTO DELIVERY_STATUS VALUES(505,'배송취소');
commit;

--PAYMENT_STATUS 결제 상태코드

INSERT INTO PAYMENT_STATUS VALUES(601,'결제완료');
INSERT INTO PAYMENT_STATUS VALUES(602,'결제취소');
commit;

--BD_STATUS 게시판 상태코드
INSERT INTO BD_STATUS VALUES(701,'정상');
INSERT INTO BD_STATUS VALUES(702,'삭제');
INSERT INTO BD_STATUS VALUES(703,'블라인드');
commit;
--BOARD_CATEGORY 게시판 카테고리코드
INSERT INTO BOARD_CATEGORY VALUES(801,'리뷰');
INSERT INTO BOARD_CATEGORY VALUES(802,'Q'||'&'||'A');
INSERT INTO BOARD_CATEGORY VALUES(803,'공지사항');
commit;
--REPLY_STATUS 댓글상태코드
INSERT INTO REPLY_STATUS VALUES(901,'정상');
INSERT INTO REPLY_STATUS VALUES(902,'삭제');
commit;


CREATE SEQUENCE SEQ_MEMBER_NO;

CREATE SEQUENCE SEQ_ADDRESS_NO;

CREATE SEQUENCE SEQ_PRODUCT_NO;

CREATE SEQUENCE SEQ_PRODUCT_IMG_NO;



CREATE SEQUENCE SEQ_ORDER_NO;

CREATE SEQUENCE SEQ_PAYMENT_NO;

CREATE SEQUENCE SEQ_BOARD_NO;

CREATE SEQUENCE SEQ_REPLY_NO;

